"""Generate a professional .docx data quality report.

All content is generated in memory. No files are written to disk.
The report states objective facts only — no invented business conclusions.
"""

from datetime import datetime
from io import BytesIO

from docx import Document
from docx.shared import Inches, Pt, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_ORIENT
import pandas as pd

from src.logger_setup import setup_logger

logger = setup_logger(__name__)

PREVIEW_ROWS = 10
MAX_OUTLIER_ROWS = 20


class ReportError(Exception):
    """Raised when report generation fails."""


def _set_page_orientation_landscape(doc: Document) -> None:
    """Set the document to landscape orientation."""
    section = doc.sections[0]
    section.orientation = WD_ORIENT.LANDSCAPE
    section.page_width, section.page_height = Cm(29.7), Cm(21.0)


def _add_footer(doc: Document) -> None:
    """Add a simple footer with generation date."""
    section = doc.sections[0]
    footer = section.footer
    footer.is_linked_to_previous = False
    paragraph = footer.paragraphs[0]
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = paragraph.add_run(f"Generated by Business Excel Automation Toolkit — {datetime.now():%Y-%m-%d}")
    run.font.size = Pt(8)
    run.font.color.rgb = None


def _add_styled_table(doc: Document, df: pd.DataFrame, header_row: bool = True) -> None:
    """Add a DataFrame as a Word table with simple styling."""
    table = doc.add_table(rows=len(df) + 1, cols=len(df.columns))
    table.style = "Light Grid Accent 1"

    if header_row:
        for col_idx, col_name in enumerate(df.columns):
            cell = table.rows[0].cells[col_idx]
            cell.text = str(col_name)
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.bold = True
                    run.font.size = Pt(9)

    for row_idx, (_, row) in enumerate(df.iterrows()):
        for col_idx, value in enumerate(row):
            cell = table.rows[row_idx + 1].cells[col_idx]
            cell.text = str(value) if value is not None else ""
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.size = Pt(9)

    doc.add_paragraph()


def generate_report(
    df: pd.DataFrame,
    stats_df: pd.DataFrame,
    source_files: list[str],
    cleaning_report: dict | None = None,
    outlier_df: pd.DataFrame | None = None,
    chart_images: list[bytes] | None = None,
    include_sections: list[str] | None = None,
) -> bytes:
    """Generate a professional .docx data quality report.

    Args:
        df: The cleaned DataFrame.
        stats_df: Summary statistics DataFrame (output of generate_summary_statistics).
        source_files: List of original source file names.
        cleaning_report: Dict from generate_cleaning_report (optional).
        outlier_df: DataFrame from summarize_outliers (optional).
        chart_images: List of PNG bytes from figure_to_bytes (optional).
        include_sections: Subset of section IDs to include. If None, all sections.
            Available: overview, quality, statistics, outliers, charts, preview, methodology.

    Returns:
        .docx file bytes.

    Raises:
        ReportError: If generation fails.
    """
    if include_sections is None:
        include_sections = ["overview", "quality", "statistics", "outliers",
                            "charts", "preview", "methodology"]

    try:
        doc = Document()
        _set_page_orientation_landscape(doc)
        _add_footer(doc)

        # ══════════════════════════════════════════════════════
        # TITLE
        # ══════════════════════════════════════════════════════
        title = doc.add_heading("Data Quality Report", level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(f"Generated: {datetime.now():%Y-%m-%d %H:%M}")
        run.font.size = Pt(10)

        doc.add_paragraph()

        # ══════════════════════════════════════════════════════
        # 1. DATASET OVERVIEW
        # ══════════════════════════════════════════════════════
        if "overview" in include_sections:
            doc.add_heading("1. Dataset Overview", level=1)

            overview = pd.DataFrame([
                ("Total Rows", f"{len(df):,}"),
                ("Total Columns", str(len(df.columns))),
                ("Source Files", ", ".join(source_files) if source_files else "N/A"),
            ], columns=["Metric", "Value"])
            _add_styled_table(doc, overview)

        # ══════════════════════════════════════════════════════
        # 2. DATA QUALITY
        # ══════════════════════════════════════════════════════
        if "quality" in include_sections:
            doc.add_heading("2. Data Quality Overview", level=1)

            if cleaning_report:
                quality_rows = [
                    ("Rows Before Cleaning", str(cleaning_report.get("rows_before", "N/A"))),
                    ("Rows After Cleaning", str(cleaning_report.get("rows_after", "N/A"))),
                    ("Duplicates Removed", str(cleaning_report.get("duplicates_removed", 0))),
                    ("Missing Values Before", str(cleaning_report.get("total_missing_before", 0))),
                    ("Missing Values After", str(cleaning_report.get("total_missing_after", 0))),
                ]
                quality_df = pd.DataFrame(quality_rows, columns=["Metric", "Value"])
                _add_styled_table(doc, quality_df)

                if cleaning_report.get("missing_actions"):
                    doc.add_heading("Cleaning Actions", level=2)
                    for action in cleaning_report["missing_actions"]:
                        doc.add_paragraph(action, style="List Bullet")
            else:
                doc.add_paragraph("No cleaning report provided.")

        # ══════════════════════════════════════════════════════
        # 3. SUMMARY STATISTICS
        # ══════════════════════════════════════════════════════
        if "statistics" in include_sections:
            doc.add_heading("3. Summary Statistics", level=1)

            if stats_df.empty:
                doc.add_paragraph("No statistics available.")
            else:
                _add_styled_table(doc, stats_df)

        # ══════════════════════════════════════════════════════
        # 4. OUTLIER SUMMARY
        # ══════════════════════════════════════════════════════
        if "outliers" in include_sections:
            doc.add_heading("4. Outlier Summary", level=1)

            if outlier_df is None or outlier_df.empty:
                doc.add_paragraph("No outliers were flagged.")
            else:
                total = len(outlier_df)
                display = outlier_df.head(MAX_OUTLIER_ROWS)
                _add_styled_table(doc, display)

                if total > MAX_OUTLIER_ROWS:
                    doc.add_paragraph(
                        f"Showing first {MAX_OUTLIER_ROWS} of {total} flagged outliers. "
                        "Review the full list in the application."
                    )

        # ══════════════════════════════════════════════════════
        # 5. CHARTS
        # ══════════════════════════════════════════════════════
        if "charts" in include_sections and chart_images:
            doc.add_heading("5. Charts", level=1)

            for i, img_bytes in enumerate(chart_images):
                try:
                    doc.add_picture(BytesIO(img_bytes), width=Inches(5.5))
                    doc.add_paragraph()
                except Exception:
                    logger.warning("Failed to embed chart image %d", i)
                    doc.add_paragraph(f"[Chart {i + 1} could not be rendered.]")

        # ══════════════════════════════════════════════════════
        # 6. DATA PREVIEW
        # ══════════════════════════════════════════════════════
        if "preview" in include_sections:
            doc.add_heading("6. Data Preview", level=1)

            preview = df.head(PREVIEW_ROWS).reset_index(drop=True)
            _add_styled_table(doc, preview)
            doc.add_paragraph(f"Showing first {min(PREVIEW_ROWS, len(df))} of {len(df):,} rows.")

        # ══════════════════════════════════════════════════════
        # 7. METHODOLOGY & LIMITATIONS
        # ══════════════════════════════════════════════════════
        if "methodology" in include_sections:
            doc.add_heading("7. Methodology & Limitations", level=1)

            doc.add_heading("Methods used", level=2)
            doc.add_paragraph(
                "This report was generated by the Business Excel Automation Toolkit. "
                "Summary statistics are computed per column based on detected data types. "
                "Outliers are detected using the IQR (interquartile range) method with a "
                "1.5x multiplier. Missing values were handled according to user-selected "
                "strategies documented in Section 2."
            )

            doc.add_heading("Limitations", level=2)
            limitations = [
                "Outlier flagging identifies statistical anomalies, not errors. "
                "A flagged value may be legitimate and should be reviewed in context.",
                "Filled missing values are estimates. The median (numeric) or mode "
                "(categorical) fill may not reflect the true value.",
                "The cleaning results depend entirely on the user's strategy choices. "
                "Different choices produce different results.",
                "This report states objective data facts only. "
                "No business conclusions are drawn automatically.",
                "Charts and statistics are based on the cleaned dataset at the time "
                "of export and may not reflect earlier versions.",
            ]
            for limitation in limitations:
                doc.add_paragraph(limitation, style="List Bullet")

        # ══════════════════════════════════════════════════════
        # FINALIZE
        # ══════════════════════════════════════════════════════
        buffer = BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        result = buffer.getvalue()

        logger.info(
            "Generated report: %.1f KB, %d sections",
            len(result) / 1024, len(include_sections),
        )
        return result

    except ReportError:
        raise
    except Exception as exc:
        logger.exception("Report generation failed")
        raise ReportError(f"Report generation failed: {exc}") from exc
